### ISSUE TITLE
Networking samples documentation updates

### ISSUE THREAD

**Issue by agansari** [zephyrproject-rtos/zephyr#11531]
While running networking samples on K64F and i.MX RT, I found the following issues in the documentation:

- Sample DHCPv4 client application
   * typo:  ‘/etc/dhcpd/dhcp.conf’ -> '/etc/dhcp/dhcpd.conf'

- gPTP Sample Application
   * -DCONF_FILE=prj.conf   -> -DCONF_FILE=prj_base.conf (filename changed)
   * submodule initialization is not mentioned, clone and follow instructions in the README
   * repo that contains gPTP code is https://github.com/ni/Open-AVB ; the one mentioned in this sample does not work

**Comment by tbursztyka** [comment]
Would you mind sending a patch fixing these?

**Comment by agansari** [comment]
Not at all :)

**Comment by jukkar** [comment]
The gptp sample issue is fixed already by commit eb9f13e3e2f8a97bbfaa0ae83705d610457b9251

**Comment by agansari** [comment]
Thanks @jukkar so only the following issues remain:

Sample DHCPv4 client application
 * typo: ‘/etc/dhcpd/dhcp.conf’ -> '/etc/dhcp/dhcpd.conf'
gPTP Sample Application
 * -DCONF_FILE=prj.conf -> -DCONF_FILE=prj_base.conf (filename changed)

**Comment by MaureenHelm** [comment]
Fixed by #12127
