### ISSUE TITLE
commit 2fb616e broke I2C on Nucleo F401RE + IKS01A2 shield

### ISSUE THREAD

**Issue by avisconti** [zephyrproject-rtos/zephyr#12544]
I2C is not working on IKS01A2 shield when the 2fb616e commit is there.
If I revert it then starts to work again.

To reproduce it you need to use theIKS01A2 shield on top of a Nucleo board.
The test to be used is currently not merged (#12398)

**Comment by avisconti** [comment]
@erwango @galak
I do not have time to debug it.
Better if the author of the commit can take a look at it.
(@cybertale )

**Comment by erwango** [comment]
@avisconti , what was nucleo reference?

**Comment by avisconti** [comment]
> @avisconti , what was nucleo reference?

Nucleo F401RE

**Comment by erwango** [comment]
`samples/shields/x_nucleo_iks01a1` is working on this same nucleo_f401re.
Do you test on this shield?

**Comment by avisconti** [comment]
No, IKS01A2 
Look at #12398

**Comment by avisconti** [comment]
> `samples/shields/x_nucleo_iks01a1` is working on this same nucleo_f401re.
> Can you test on this shield?

Ah, it's a request.
OK

**Comment by erwango** [comment]
So, I had some tests and I finally have same status before and after incriminated SHA1.
I'll try to see if I can get hands on x_nucleo_iks01a2 shield, but in the mean time, it would be good you could have other tests on your side as well.

**Comment by erwango** [comment]
@avisconti, I haven't found x_nucleo_iks01a2, so I've stripped out x_nucleo_iks01a2 sample to keep only hts221 code and I'm testing with x_nucleo_iks01a1 shield.
This is actually working even with 2fb616e commit.

Can you reproduce the error in similar conditions?
Or is the error specific to other sensor?

**Comment by avisconti** [comment]
@erwango 
This morning I was about to push again the #11188 and before doing that I also rebase to the latest
commit of zephyr master. Well, I found that the 2fb616e is breaking also the microphone sample.
If I revert that commit everything is working again. So, I believe that there is something in that commit
that I need to investigate. I'm depressed..... but hopefully it will not tke that long.

**Comment by explora26** [comment]
Hi, the 2fb616efbef663a5912673507031e3cf102ec828 also breaking the hello world example on stm32_min_dev board, there is nothing output from UART1.

**Comment by erwango** [comment]
@explora26 , I'm working on a fix. Can you test with https://github.com/erwango/zephyr/commits/fix_gpio and see if solving your issue?

**Comment by explora26** [comment]
@erwango , I just test it, but the issue still not fixed.

**Comment by avisconti** [comment]
@erwango 
In my case it is fixed, at least the microphone sample. But I'm confident also for the other setup.

@explora26 
What STM32 architecture you are based on?

**Comment by erwango** [comment]
@avisconti , @explora26 , I've pushed a clean up commit in https://github.com/erwango/zephyr/commits/fix_gpio , if you have some time to confirm it still works would be nice.
I'll do full non regression and then push a PR later today

**Comment by explora26** [comment]
@avisconti , It's stm32f103c8t6.

@erwango , I tested it again, but unfortunately it's still not work.

**Comment by erwango** [comment]
@explora26 , if you have access to gdb, can you do the following before and after the change?
```
(gdb)x /4x 0x40010800
0x40010800:	0x44444944	0x88844444	0x0000dfdc	0x0000a000
```

**Comment by pabigot** [comment]
@erwango +1 for getting your `fix_pgio_refactor` branch merged.  It resolves the inability to see any I2C devices on `nucleo_l476rg` that I lost significant time trying to understand when testing #12567.

**Comment by explora26** [comment]
@erwango 
Here is the registers dump of https://github.com/erwango/zephyr/commits/fix_gpio
```
(gdb) x /4x 0x40010800
0x40010800:	0x44444444	0x88844444	0x0000dffc	0x0000a000
```

**Comment by erwango** [comment]
@explora26, txs.
Is that dump done at boot or following break in Idle (with Crtl-C)?
Can you do the same procedure before the commit that introduced the issue?
