### ISSUE TITLE
[Coverity CID :190961]Error handling issues in /subsys/bluetooth/host/mesh/prov.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#13855]
Static code scan issues seen in File: /subsys/bluetooth/host/mesh/prov.c
 Category: Error handling issues
 Function: prov_data
 Component: Bluetooth
 CID: 190961
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
This is marked as fixed by #12338 in Coverity. Why was this issue opened?

**Comment by mandarcthorat1** [comment]
Commit was not fixing the issue reported by coverity. The problem is still valid and detected by latest scan

**Comment by jhedberg** [comment]
@mandarcthorat1 seems like I may have gotten two different issues mixed up. Anyway, this is a simple fix - will submit a PR in a moment.
