### ISSUE TITLE
net: ipv6: tcp: unexpected reply to malformed HBH in TCP/IPv6 SYN

### ISSUE THREAD

**Issue by rmstoi** [zephyrproject-rtos/zephyr#16323]
If Zephyr receives TCP/IPv6 SYN with malformed Hop-by-Hop having wrong length, it replies with ICMPv6 Destination Unreachable (Port unreachable). Since the length of Hop-by-Hop option is wrong, Zephyr should instead send ICMP parameter problem message or silently drop the packet.

Note that it this packet is dropped for ICMPv6 and UDPv6.

[bad-hbho-len.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3207309/bad-hbho-len.pcap.gz)

**Comment by jukkar** [comment]
@rmstoi can you check this one, I fixed the TCP option calc len which hopefully fixes this.

**Comment by rmstoi** [comment]
@jukkar I checked it still fails. The problem is that unknown option 0x42 in HBH has wrong length, and because of this packet must be dropped.

**Comment by jukkar** [comment]
We can have this for 2.0 so adjusting target.
