### ISSUE TITLE
application_development test pollutes source directory

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#4925]
Output of 'git status' after running sanitycheck:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	tests/application_development/gen_inc_file/src/file.bin.gz.inc
	tests/application_development/gen_inc_file/src/file.bin.inc
```

The build system needs to place all generated artifacts in the output directory, not mixed in with the source tree

**Comment by nashif** [comment]
wasn't this just fixed by 965f78088fd57bfabfb74943b22613973d69f85b?

**Comment by andrewboie** [comment]
might be. let me rebase my tree and re-test

**Comment by andrewboie** [comment]
@nashif no this is not fixed

reproduce by running "sanitycheck -i"

**Comment by andrewboie** [comment]
This is what I am seeing now:

```
	samples/application_development/external_lib/mylib/src/mylib_project-stamp/
	samples/application_development/external_lib/mylib/tmp/
```

**Comment by SebastianBoe** [comment]
Sorry about creating paperwork, should of course not have been like this in the first place.
