### ISSUE TITLE
[Coverity CID: 179986] Null pointer dereferences in /subsys/bluetooth/host/mesh/access.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#5116]
Static code scan issues seen in File: /subsys/bluetooth/host/mesh/access.c
 Category: Null pointer dereferences
 Function: bt_mesh_model_publish
 Component: Bluetooth
 CID: 179986
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
Already fixed in the master branch

**Comment by nashif** [comment]
@jhedberg  looking at the code, this one seems to be still there in coverity and is not fixed, can you take a look at this?
