### ISSUE TITLE
samples/subsys/tracing/ sample.tracing.gpio fails on stm32 and nordic boards with gpio_loopback fixture

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#82733]
**Describe the bug**
Running the    samples/subsys/tracing/sample.tracing.gpio   on stm32 boards where the fixture gpio_loopback is set 
will fail.

--> the **gpio_loopback** is set for the target board in order to pass tests/drivers/i2s/i2s_api or test/drivers/gpio/gpio_basic_api/ or tests/drivers/uart/uart_async_api

When executing the samples/subsys/tracing/sample.tracing.gpio, the console gives the following output which is not declared as "PASSED" :

```
...
sys_trace_idle_user
sys_trace_idle_user
thread_a: Hello World from nucleo_g474re!
sys_trace_idle_user
sys_trace_idle_user
sys_trace_idle_user
sys_trace_idle_user
sys_trace_idle_user
sys_trace_idle_user
thread_b: Hello World from nucleo_g474re!
sys_trace_idle_user
...

```

**To Reproduce**
1. west build -p auto -b nucleo_g474re samples/subsys/tracing  -DCONF_FILE="prj_gpio.conf" -DEXTRA_DTC_OVERLAY_FILE="gpio.overlay" 
2. west flash

**Expected behavior**
Should the testcase be executed on that board ?

**Impact**
Test campaign fails on each target board where the gpio_loopback fixture is set

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)   ubuntu 
 - Toolchain (e.g Zephyr SDK, ...)  SDK 0.16.8
 - Commit SHA or Version used  ef6f804d8f2648935afadaab09b511913ffd9f4c

**Comment by masz-nordic** [comment]
Incorrect assignment, this bug is STM specific.

**Comment by katgiadla** [comment]
The same issue is visible on:
- `nrf52dk/nrf52832`
- `nrf52840dk/nrf52840`
- `nrf5340dk/nrf5340/cpuapp`
- `nrf9160dk@0.14.0/nrf9160`
- `nrf54l15dk/nrf54l15/cpuapp`
- `nrf54l15dk/nrf54l05/cpuapp`
- `nrf54l15dk/nrf54l10/cpuapp`
- `nrf54l15dk/nrf54l15/cpuflpr`

**Comment by fabiobaltieri** [comment]
should be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/82648, tentatively closing

**Comment by katgiadla** [comment]
> The same issue is visible on:
nrf52dk/nrf52832
nrf52840dk/nrf52840
nrf5340dk/nrf5340/cpuapp
nrf9160dk@0.14.0/nrf9160
nrf54h20dk@0.9.0/nrf54h20/cpuapp
nrf54h20dk@0.9.0/nrf54h20/cpurad

The issue still occurs on the all nordic platforms.

**Comment by fabiobaltieri** [comment]
@ydamigos can you take a look?

**Comment by ydamigos** [comment]
@fabiobaltieri  It seems to be a different issue. The output prints continuously:
```
sys_trace_isr_enter_user: 0
sys_trace_isr_exit_user: 0
...
```
It look likes it stays in an IRQ loop.

**Comment by fabiobaltieri** [comment]
thanks @ydamigos, @katgiadla can you reopen a different one? (just to be clear I'm just triaging here)
